### ISSUE TITLE
请问UbertPiplines代码在哪里呢？

### ISSUE THREAD

**Issue by czhcc** [LYR-kami/PaddleNLPDemo#1]
from fengshen import UbertPiplines
这行出错

**Comment by czhcc** [comment]
没事了，名称改为UbertPipelines了

**Comment by FFinchR** [comment]
你好，感谢你对本repo的关注。
建议在官方的repo查看，本repo兴趣使然，已经停更很久了。
https://github.com/IDEA-CCNL/Fengshenbang-LM
https://github.com/IDEA-CCNL/Fengshenbang-doc/blob/main/source/docs/%E4%BA%8C%E9%83%8E%E7%A5%9E%E7%B3%BB%E5%88%97/Erlangshen-Ubert-110M-Chinese.md
